In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns


from copy import deepcopy

import statsmodels.api as sm
from datetime import datetime

import random
random.seed(0)
pd.set_option('display.max_columns', 500)

### define the data frame function, it convert association files into pandas data frame

In [2]:
def ar_df(association_rules):
    association_rules=list(association_rules)
    ar={}
    ar['item_base']=[]
    ar['item_add']=[]
    ar['support']=[]
    ar['confidence']=[]
    ar['lift']=[]

    for item in association_rules:
        item_base=[x for x in item[2][0][0]]
        ar['item_base'].append(item_base)

        item_add=[x for x in item[2][0][1]]
        ar['item_add'].append(item_add)

        support=item[1]
        ar['support'].append(support)

        confidence=item[2][0][2]
        ar['confidence'].append(confidence)

        lift=item[2][0][3]
        ar['lift'].append(lift)

    ar=pd.DataFrame(ar)

    return ar

In [67]:
#https://stackabuse.com/association-rule-mining-via-apriori-algorithm-in-python/
from apyori import apriori
from efficient_apriori import apriori as ef_ap

### USJH dataset 
the result is not consistence with R!

In [4]:
usjh=pd.read_csv('USJH.csv')

/Users/jialanzhu/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [9]:
usjh=usjh.drop(['Unnamed: 0','Unnamed: 0.1','Unnamed: 0.1.1'],axis=1)

In [10]:
usjh.head()

,name,financial_status,paid_at,fulfillment_status,accepts_marketing,currency,subtotal,shipping,taxes,total,discount_code,discount_amount,shipping_method,created_at,lineitem_quantity,lineitem_name,lineitem_price,lineitem_compare_at_price,lineitem_sku,lineitem_fulfillment_status,shipping_street,shipping_address1,shipping_company,shipping_city,shipping_zip,shipping_province,shipping_country,notes,cancelled,payment_method,refunded_amount,vendor,risk_level,source,color,category
0,#4746,paid,2018-07-16 12:31:00,unfulfilled,yes,usd,100.5,13.64,0.0,114.14,nodiscount,0.0,fedex ground,2018-07-16 12:31:00,1,turquoise crystal rhinestone ring - gdtq,3.50,3.50,16646,pending,475 calle retama,475 calle retama,t-trendz,brownsville,78520,tx,us,nonotes,1,shopify payments,0.0,us jewelry house,low,web,gdtq,ring
1,#4746,paid,2018-07-16 12:31:00,unfulfilled,yes,usd,100.5,13.64,0.0,114.14,nodiscount,0.0,fedex ground,2018-07-16 12:31:00,1,turquoise crystal rhinestone ring - gdtq,3.25,3.25,16649,pending,475 calle retama,475 calle retama,t-trendz,brownsville,78520,tx,us,nonotes,1,shopify payments,0.0,us jewelry house,low,web,gdtq,ring
2,#4746,paid,2018-07-16 12:31:00,unfulfilled,yes,usd,100.5,13.64,0.0,114.14,nodiscount,0.0,fedex ground,2018-07-16 12:31:00,1,tri tone cubic zirconia paved simple band ring...,10.50,10.50,27281,pending,475 calle retama,475 calle retama,t-trendz,brownsville,78520,tx,us,nonotes,1,shopify payments,0.0,impression,low,web,size 8,ring
3,#4746,paid,2018-07-16 12:31:00,unfulfilled,yes,usd,100.5,13.64,0.0,114.14,nodiscount,0.0,fedex ground,2018-07-16 12:31:00,1,geometric tortoise link long necklace - brown,9.75,9.75,27976,pending,475 calle retama,475 calle retama,t-trendz,brownsville,78520,tx,us,nonotes,1,shopify payments,0.0,ella,low,web,brown,necklace
4,#4746,paid,2018-07-16 12:31:00,unfulfilled,yes,usd,100.5,13.64,0.0,114.14,nodiscount,0.0,fedex ground,2018-07-16 12:31:00,1,acetate skinny bangle bracelet with front clos...,5.25,5.25,28943,pending,475 calle retama,475 calle retama,t-trendz,brownsville,78520,tx,us,nonotes,1,shopify payments,0.0,stylist,low,web,white/brown,bracelet

### investigate:
-  lineitem_name
-  category
-  vendor
-  vendor:category

### 1. lineitem_name

In [142]:
#group by order # and select linitem_name column
grouped_df1 = usjh.groupby('name')['lineitem_name']
#the grouped data frame is like dictionary, make them a nested list
lis1 = []
for key, item in grouped_df1:
    lis1.append(set(item))
#run the Apriori, if computation taking to long, increase the minimum support
rules1 = apriori(lis1, min_support=0.002, min_confidence=0.2, min_lift=3, min_length=1)

In [69]:
ef_ap?

In [20]:
#show association rules in a data frame
ar1=ar_df(rules1)

In [29]:
ar1=ar1.sort_values('lift', ascending=False)
print(ar1.shape)
ar1.head()

(629, 5)

,item_base,item_add,support,confidence,lift
333,[thread ball faceted bead tassel drop earrings...,[thread ball faceted bead tassel drop earrings...,0.002475,1.000000,404.111111
40,[beautiful message bracelet - gold],[beautiful message bracelet - silver],0.002475,0.900000,363.700000
329,[suede baseball cap - burgundy],[suede baseball cap - khaki],0.002200,0.888889,359.209877
51,[button multi ear studs set - matte black-matt...,[button multi ear studs set - rose gold-gold],0.002200,0.727273,330.636364
77,[cz ball thread tassel earrings - black],[cz ball thread tassel earrings - purple],0.002200,0.888889,323.288889

### 2. category

In [75]:
#group by order # and select category column
grouped_df2 = usjh.groupby('name')['category']
#the grouped data frame is like dictionary, make them a nested list
lis2 = []
for key, item in grouped_df2:
    lis2.append(set(item))
#run the Apriori, if computation taking to long, increase the minimum support
itemsets2, rules2 = ef_ap(lis2, min_support=0.02, min_confidence=0.2)

In [83]:
# Print out every rule with 2 items on the left hand side,
# 1 item on the right hand side, sorted by lift

In [84]:
#show association rules in a data frame
ar2=ar_df(rules2)

TypeError: 'Rule' object does not support indexing

In [85]:
ar2=ar2.sort_values('lift', ascending=False)
print(ar2.shape)

(63, 5)

### create ready to use data frame for flask

In [180]:
#the data frame is sorted by support
rules=pd.read_csv("vendor_cate_rules.csv").drop('Unnamed: 0',axis=1).sort_values('support',ascending=False)

In [122]:
print(rules.shape)
rules.head()

(2138, 6)

,lhs,rhs,support,confidence,lift,count
4,{},{us jewelry house:necklace},0.507561,0.507561,1.000000,1846
3,{},{us jewelry house:earring},0.391531,0.391531,1.000000,1424
2,{},{us jewelry house:bracelet},0.275502,0.275502,1.000000,1002
433,{us jewelry house:earring},{us jewelry house:necklace},0.251306,0.641854,1.264584,914
434,{us jewelry house:necklace},{us jewelry house:earring},0.251306,0.495125,1.264584,914

In [123]:
rules['lhs'].iloc[0]

'{}'

In [124]:
#remove the empty rules
rules_=rules[rules['lhs']!='{}']

In [125]:
#remove the {}
rules_['lhs']=rules_['lhs'].replace('[{}]', '', regex=True)
rules_['rhs']=rules_['rhs'].replace('[{}]', '', regex=True)

/Users/jialanzhu/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/jialanzhu/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [179]:
rules_.head()

,lhs,rhs,support,confidence,lift,count
433,us jewelry house:earring,us jewelry house:necklace,0.251306,0.641854,1.264584,914
434,us jewelry house:necklace,us jewelry house:earring,0.251306,0.495125,1.264584,914
431,us jewelry house:bracelet,us jewelry house:necklace,0.204014,0.740519,1.458975,742
432,us jewelry house:necklace,us jewelry house:bracelet,0.204014,0.401950,1.458975,742
429,us jewelry house:bracelet,us jewelry house:earring,0.162497,0.589820,1.506444,591

### create all item dictionary vendor:category : items

In [136]:
usjh_all=pd.read_csv("USJH_rules.csv").drop(['Unnamed: 0','X','Unnamed..0','Unnamed..0.1'], axis=1)

/Users/jialanzhu/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [138]:
usjh_all.head()

,name,financial_status,paid_at,fulfillment_status,accepts_marketing,currency,subtotal,shipping,taxes,total,discount_code,discount_amount,shipping_method,created_at,lineitem_quantity,lineitem_name,lineitem_price,lineitem_compare_at_price,lineitem_sku,lineitem_fulfillment_status,shipping_street,shipping_address1,shipping_company,shipping_city,shipping_zip,shipping_province,shipping_country,notes,cancelled,payment_method,refunded_amount,vendor,risk_level,source,color,category,vendor_category
0,#4746,paid,2018-07-16 12:31:00,unfulfilled,yes,usd,100.5,13.64,0.0,114.14,nodiscount,0.0,fedex ground,2018-07-16 12:31:00,1,turquoise crystal rhinestone ring - gdtq,3.50,3.50,16646,pending,475 calle retama,475 calle retama,t-trendz,brownsville,78520,tx,us,nonotes,1,shopify payments,0.0,us jewelry house,low,web,gdtq,ring,us jewelry house:ring
1,#4746,paid,2018-07-16 12:31:00,unfulfilled,yes,usd,100.5,13.64,0.0,114.14,nodiscount,0.0,fedex ground,2018-07-16 12:31:00,1,turquoise crystal rhinestone ring - gdtq,3.25,3.25,16649,pending,475 calle retama,475 calle retama,t-trendz,brownsville,78520,tx,us,nonotes,1,shopify payments,0.0,us jewelry house,low,web,gdtq,ring,us jewelry house:ring
2,#4746,paid,2018-07-16 12:31:00,unfulfilled,yes,usd,100.5,13.64,0.0,114.14,nodiscount,0.0,fedex ground,2018-07-16 12:31:00,1,tri tone cubic zirconia paved simple band ring...,10.50,10.50,27281,pending,475 calle retama,475 calle retama,t-trendz,brownsville,78520,tx,us,nonotes,1,shopify payments,0.0,impression,low,web,size 8,ring,impression:ring
3,#4746,paid,2018-07-16 12:31:00,unfulfilled,yes,usd,100.5,13.64,0.0,114.14,nodiscount,0.0,fedex ground,2018-07-16 12:31:00,1,geometric tortoise link long necklace - brown,9.75,9.75,27976,pending,475 calle retama,475 calle retama,t-trendz,brownsville,78520,tx,us,nonotes,1,shopify payments,0.0,ella,low,web,brown,necklace,ella:necklace
4,#4746,paid,2018-07-16 12:31:00,unfulfilled,yes,usd,100.5,13.64,0.0,114.14,nodiscount,0.0,fedex ground,2018-07-16 12:31:00,1,acetate skinny bangle bracelet with front clos...,5.25,5.25,28943,pending,475 calle retama,475 calle retama,t-trendz,brownsville,78520,tx,us,nonotes,1,shopify payments,0.0,stylist,low,web,white/brown,bracelet,stylist:bracelet

In [145]:
x=usjh_all.groupby('vendor_category')['lineitem_name']
usjh_all_item={}

for key, value in x:
    usjh_all_item[key]=set(value)

In [152]:
len(usjh_all_item.keys())

326

### how to perform recommandation
1. create an order list
2. for each item in the list, create an list containing its associated items (the highest support)
3. check if there is sale (discount) among these associated items
   a) if yes, recommand sale items
   b) if no, return the highest support item

In [159]:
#create sale list, randomly select 100 items as sale item
sale=usjh_all[['lineitem_name']].sample(100)
sale.head()

                                      lineitem_name
58436          glass stone statement choker - white
75310               train of beads necklace - multi
27718      bohemian beads magnetic bracelet - brown
47066              pompom and tassel necklace - jet
28589  multi leather layered bohemian necklace - bk

In [178]:
#create sale vendor: category based on sale items
sale_vc=[]
for item in sale['lineitem_name']:
    sale_vc.append(usjh_all[usjh_all['lineitem_name']==item].vendor_category.iloc[0])
    
sale_vc=set(sale_vc)

In [160]:
#create a dummy order list
order=usjh_all[['lineitem_name']].sample(10)

In [185]:
order

                                           lineitem_name
21262        5 rings filigree multi package set - silver
71407             tribal charm mini hoop earrings - gold
15074                     leaf pendant bohemian necklace
56322            large flowers statement necklace - pink
33582              boho chic chain tassel necklace - rgd
13508                    religious 4 layers necklace set
20258  sliding knot adjustable tassel necklace - turq...
12360  lightweight geometric cutout tortoise drop ear...
226          top handle holographic vinyl jelly mini bag
20138            lightweight flower stud earrings - grey

In [184]:
#look up associated item category
assoc_rules={}
for item in order['lineitem_name']:
    assoc_rules['rhs']=rules_[rules_['lhs']==item].rhs.iloc[0]
    assoc_rules['support']=rules_[rules_['lhs']==item].support.iloc[0]

IndexError: single positional indexer is out-of-bounds